# from .dpf_ssw_aligner_rspy import PyCigar as PyCigar, PyAlign as PyAlign, py_ssw_align as py_ssw_align

class PyCigar:
    def get_seq(self) -> list[int]: ...
    def get_length(self) -> int: ...

class PyAlign:
    def get_score1(self) -> int: ...
    def get_score2(self) -> int: ...
    def get_ref_begin1(self) -> int: ...
    def get_ref_end1(self) -> int: ...
    def get_read_begin1(self) -> int: ...
    def get_read_end1(self) -> int: ...
    def get_ref_end2(self) -> int: ...
    def get_cigar(self) -> PyCigar: ...
    def get_flag(self) -> int: ...

class PyProfile:
    def __init__(self, read: list[int], read_len: int, mat: list[int], n: int, score_size: int) -> None: ...

def py_ssw_align(
    prof: PyProfile,
    ref_seq: list[int],
    ref_len: int,
    weight_gap_o: int,
    weight_gap_e: int,
    flag: int,
    filters: int,
    filterd: int,
    mask_len: int,
) -> PyAlign | None: ...
