[project]
name = "dpf_sanger_sequencing"
description="A library for interpreting sanger sequencing data"
requires-python = ">=3.11"
authors = [{name = "Danny Farrell", email = "danpf@uw.edu"}]
dependencies = ["biopython", "requests", "sqlalchemy"]
version="1.0.0"
