---
name: "CI & CD"

on:
  workflow_dispatch:
  pull_request:
  release:
    types:
    - published
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test-and-build-dpf-ssw-aligner:
    name: "Build & Test dpf-ssw-aligner-pyrs"

    steps:
      - uses: actions/checkout@v3

      # QEMU enables building/testing for non-native architectures (ie arm64)
      # at the cost of speed
      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Build, Test, and Upload dpf-ssw-aligner-rs
        run: python ./mono.py cicd_dpf_ssw_aligner

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/dpf_ssw_aligner*.whl

  test-and-build-dpf-mrcfile:
    name: "Build & Test dpf-mrcfile"

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Build, Test, and Upload dpf-mrcfile
        run: python ./mono.py cicd_dpf_ssw_aligner

      - uses: actions/upload-artifact@v3
        if: runner.os == 'Linux'
        with:
          path: ./wheelhouse/dpf_mrcfile*.whl
