---
name: "CI & CD"

on:
  workflow_dispatch:
  pull_request:
  release:
    types:
    - published

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

  test-and-build:
    name: "Build & Test"
    needs: "generate-wheels-matrix"
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]
        project_folder: ["./src/python/dpf-ssw-aligner-rs"]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      # QEMU enables building/testing for non-native architectures (ie arm64)
      # at the cost of speed
      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
          package-dir: src/python/dpf-ssw-aligner-rs
          # package-dir: src/python/dpf-ssw-aligner-rs

      - name: Build & test wheels
        uses: pypa/cibuildwheel@v2.12.3

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/dpf_ssw_aligner*.whl
