---
name: "CI & CD"

on:
  workflow_dispatch:
  pull_request:
  release:
    types:
    - published
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test-and-build-dpf-ssw-aligner:
    name: "Build & Test dpf-ssw-aligner-pyrs"
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]
        project_folder: ["./src/python/dpf-ssw-aligner-rs"]
        python-version: ['cp310', 'cp311']
    runs-on: ${{ matrix.os }}
    env:
      CIBW_ENVIRONMENT: 'PATH="$PATH:$HOME/.cargo/bin"'
      CIBW_SKIP: "p*-win* *-win32 *-win_arm64 *-musllinux_*"

    steps:
      - uses: actions/checkout@v3

      # QEMU enables building/testing for non-native architectures (ie arm64)
      # at the cost of speed
      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Install latest nightly
        uses: dtolnay/rust-toolchain@nightly

      - name: Build & test wheels dpf-ssw-aligner-rs wheels
        uses: pypa/cibuildwheel@v2.12.3
        with:
          package-dir: src/python/dpf-ssw-aligner-rs
        env:
          CIBW_BUILD: '${{ matrix.python-version }}-*'
          # we build for "alt_arch_name" if it exists, else 'auto'
          CIBW_ARCHS: ${{ matrix.alt_arch_name || 'auto' }}
          CIBW_ENVIRONMENT: 'PATH="$HOME/.cargo/bin:$PATH" CARGO_TERM_COLOR="always"'
          CIBW_ENVIRONMENT_WINDOWS: 'PATH="$UserProfile\.cargo\bin;$PATH"'
          CIBW_BEFORE_ALL_WINDOWS: "rustup target add x86_64-pc-windows-msvc i686-pc-windows-msvc"
          CIBW_BEFORE_ALL_MACOS: "rustup target add aarch64-apple-darwin x86_64-apple-darwin"
          CIBW_BEFORE_BUILD: rustup show
          CIBW_BEFORE_BUILD_LINUX: >
            curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain=nightly --profile=minimal -y &&
            rustup show
          # CIBW_TEST_SKIP: '*-macosx_universal2:arm64'
          CIBW_BUILD_VERBOSITY: 1

      - name: Build sdist
        run: pipx run build --sdist --outdir wheelhouse src/python/dpf-ssw-aligner-rs

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/dpf_ssw_aligner*.whl

  test-and-build-dpf-mrcfile:
    name: "Build & Test dpf-mrcfile"
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]
        project_folder: ["./src/python/dpf-mrcfile"]
        python-version: ['cp310', 'cp311']
    runs-on: ${{ matrix.os }}
    env:
      CIBW_SKIP: "p*-win* *-win32 *-win_arm64 *-musllinux_*"

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest build src/python/dpf-mrcfile

      - name: Test with pytest
        run: |
          pytest src/python/dpf-mrcfile/test

      - name: Build sdist
        run: python -m build -o wheelhouse src/python/dpf-mrcfile

      - uses: actions/upload-artifact@v3
        if: runner.os == 'Linux'
        with:
          path: ./wheelhouse/dpf_mrcfile*.whl
